### ISSUE TITLE
chests don't connect to boublechests + suggestion

### ISSUE THREAD

**Issue by WorldsOfRosefire** [xanthian/variantchests#1]
first - great job! I was looking for that! your variant mods are great! 
I also have 2 suggestions. 
1st can they share the same creative tab if more "variant wood"  mods are installed?
2nd you are missing the lectern for the libarian villager in your variant wood series

well the title says everything, I can not connect them to double chests.. other modded chests from better nether are working.
minecraft 1.20.1 fabric 0.14.22

**Comment by xanthian** [comment]
Double chests aren't working yet, but they will eventually :)

I had thought about writing an API to share the same creative tab, however I also released Variant Vanilla Blocks which includes the vast majority of blocks (not chests - yet)

I have done Lecterns in the above mod, but not released individually.

https://legacy.curseforge.com/minecraft/mc-mods/variant-vanilla-blocks

**Comment by GabbyDG2805** [comment]
Just want to express that I'm very much looking forward to the double chest functionality

**Comment by xanthian** [comment]
I've not started as I've been attempting to port mods over to Forge.
I'll take a look at this today and see how far I get..
Lets aim for in the next 2 weeks?

**Comment by xanthian** [comment]
![image](https://github.com/xanthian/variantchests/assets/7688001/804dbdf8-c9f7-41cb-b0d5-9631d0fe66a1)

made progress :)
need to test, maybe release tomorrow

**Comment by mrGRINCH** [comment]
> ![image](https://user-images.githubusercontent.com/7688001/272405826-804dbdf8-c9f7-41cb-b0d5-9631d0fe66a1.png)
> 
> made progress :) need to test, maybe release tomorrow

That's awesome. They're looking great!

My friends will be super happy to hear the progress.

**Comment by xanthian** [comment]
@WorldsOfRosefire 
@mrGRINCH 
@GabbyDG2805 

Done!

https://legacy.curseforge.com/minecraft/mc-mods/variantchests/files/4782312

**Comment by mrGRINCH** [comment]
Thank you for your work!
