### ISSUE TITLE
Support for Regions Unexplored

### ISSUE THREAD

**Issue by NytSong** [xanthian/variantchests#2]
I did see you were going to add support for Regions Unexplored at some point in the near future, but, until then, it would be great to continue to be able to craft the vanilla chests  with wood this mod doesn't currently support.

I'm wondering if you have any workarounds available to achieve this until you do have official support.

**Comment by xanthian** [comment]
Apologies, no workarounds I can think of.
Maybe install polymorph mod and make a datapack to include #minecraft:planks in a recipe for the vanilla chest.
I'm currently updating Beehives, which will be complete today, I'll then work on chests. Should be done 'hopefully' this week

**Comment by NytSong** [comment]
Thanks for the suggestion, and I look forward to the update.

**Comment by xanthian** [comment]
Quick update for you, 
progress has been made, textures are taking a very long time, I forgot how many variants there are in Regions Unexplored.
Hopefully ready monday
![image](https://github.com/xanthian/variantchests/assets/7688001/0cf87817-efe4-492a-87ae-320c990234e0)

**Comment by NytSong** [comment]
Thanks for the update. And yes, it does have a whole lot to work with. All of us who use this mod appreciate your work.

**Comment by xanthian** [comment]
aaaaaaaaand done!
uploading..
![image](https://github.com/xanthian/variantchests/assets/7688001/62e52098-3410-4651-96c3-367f6c8dad7b)
