### ISSUE TITLE
Biomemakeover chests missing

### ISSUE THREAD

**Issue by abdmoh123** [xanthian/variantchests#3]
Your other variant blocks mods have biomemakeover blocks but it seems that it's missing from this one.
- Blighted Balsa Chest
- Willow Chest
- Swamp Cypress Chest
- Ancient Oak Chest

**Comment by xanthian** [comment]
chests are WIP, takes a bit longer to add

**Comment by abdmoh123** [comment]
No problem, I just thought it was an oversight

**Comment by xanthian** [comment]
done
